services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - "8080:8080"
    networks:
      - biblioteca
  
  db:
    image: postgres:latest
    container_name: biblioteca-db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - biblioteca-data:/var/lib/postgresql/data
    networks:
      - biblioteca

volumes:
  biblioteca-data:
    
networks:
  biblioteca:
    driver: bridge